# Rebuilds data/gis.js (loaded by index.html) from the JSON files in data/gis/.
# Run from the repo root:  python3 tools/build_gis.py
#
# Coordinates: local metres × 10 (integers), x = east, y = north,
# origin at 34.76799°E, 32.06322°N (centre of the block). Source: Tel Aviv-Yafo municipal GIS
# (https://gisn.tel-aviv.gov.il/arcgis/rest/services/IView2/MapServer), fetched 29/09/2026.
#
# buildings.json    [id, floors, height_m, dsm_mean_m, dsm_max_m, ground_level_m, year_built, ring]
# parcels.json      [gush, helka, registered_area_m2, ring]
# preservation.json [addresses, strict_restrictions(0/1), ring]
# streets.json      [name, type, [paths]]
# addresses.json    [street, number, helka, x, y]
# trees.json        [species, address, x, y]
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'data', 'gis')
parts = {k: json.load(open(os.path.join(SRC, f), encoding='utf-8')) for k, f in (
    ('B', 'buildings.json'), ('P', 'parcels.json'), ('S', 'preservation.json'),
    ('R', 'streets.json'), ('A', 'addresses.json'), ('T', 'trees.json'))}
out = os.path.join(ROOT, 'data', 'gis.js')
with open(out, 'w', encoding='utf-8') as f:
    f.write('// Generated by tools/build_gis.py — edit data/gis/*.json and re-run.\n')
    f.write('window.GIS = ' + json.dumps(parts, ensure_ascii=False, separators=(',', ':')) + ';\n')
print('wrote', os.path.relpath(out, ROOT))
